inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 80
  IgnoredPatterns: ['\A#', '#']
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# Files to ignore
AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - 'tmp/**/*'
    - '.git/**/*'
